### ISSUE TITLE
Remove EnumerableExtensions duplicated by AndcultureCode.CSharp.Extensions

### ISSUE THREAD

**Issue by wintondeshong** [AndcultureCode/AndcultureCode.CSharp.Core#18]
~[Coverage report](https://codecov.io/gh/AndcultureCode/AndcultureCode.CSharp.Core/src/master/src/AndcultureCode.CSharp.Core/Extensions/IResultExtensions.cs)~

~- public static string Join(this IEnumerable<KeyValuePair<string, string>> list, string keyValueDelimiter, string delimiter = ", ")~
~- public static string Join(this KeyValuePair<string, string> pair, string delimiter~

These extension methods have been moved to [AndcultureCode.CSharp.Extensions](https://github.com/AndcultureCode/AndcultureCode.CSharp.Extensions/issues/27). Remove them from this project and update the package dependency if needed.

**Comment by brandongregoryscott** [comment]
Now that these are ported to `AndcultureCode.CSharp.Extensions` (and tested), we can probably change this issue to remove the duplicated extension methods.
