### ISSUE TITLE
Add/fix XML doc comments for Cultures

### ISSUE THREAD

**Issue by brandongregoryscott** [AndcultureCode/AndcultureCode.CSharp.Core#34]
See warning list from a recent build:

```
Cultures\EnglishUnitedStates.cs(6,18): warning CS1591: Missing XML comment for publicly visible type or member 'EnglishUnitedStates' [C:\Users\bscot\acc\origin\AndcultureCode.CSharp.Core\src\AndcultureCode.CSharp.Core\AndcultureCode.CSharp.Core.csproj]
Cultures\EnglishUnitedStates.cs(8,32): warning CS1591: Missing XML comment for publicly visible type or member 'EnglishUnitedStates.Code' [C:\Users\bscot\acc\origin\AndcultureCode.CSharp.Core\src\AndcultureCode.CSharp.Core\AndcultureCode.CSharp.Core.csproj]
Cultures\EnglishUnitedStates.cs(9,30): warning CS1591: Missing XML comment for publicly visible type or member 'EnglishUnitedStates.IsDefault' [C:\Users\bscot\acc\origin\AndcultureCode.CSharp.Core\src\AndcultureCode.CSharp.Core\AndcultureCode.CSharp.Core.csproj]
Cultures\SpanishSpain.cs(6,18): warning CS1591: Missing XML comment for publicly visible type or member 'SpanishSpain' [C:\Users\bscot\acc\origin\AndcultureCode.CSharp.Core\src\AndcultureCode.CSharp.Core\AndcultureCode.CSharp.Core.csproj]
Cultures\SpanishSpain.cs(8,32): warning CS1591: Missing XML comment for publicly visible type or member 'SpanishSpain.Code' [C:\Users\bscot\acc\origin\AndcultureCode.CSharp.Core\src\AndcultureCode.CSharp.Core\AndcultureCode.CSharp.Core.csproj]
```

Add or fix comments as needed to reduce the number of warnings.

If you're not sure what a function/field does and you're an andculture employee, feel free to ask to pair with another engineer or in Slack to figure out how to best document the actor, or move on to another area. 

If you're not an andculture employee, try to add something to the best of your ability - otherwise, feel free to add in a TODO comment with a link to this issue so another engineer can search for those in the code base and fill them in with an actual description. For example:

```CS
/// <summary>
/// TODO https://github.com/AndcultureCode/AndcultureCode.CSharp.Core/issues/38
/// </summary>
/// <param name="key"></param>
/// <param name="value"></param>
public void Add(TKey key, TValue value)
...
```

**Comment by MaurizioPz** [comment]
I'd like to take also this. Is it ok?

**Comment by brandongregoryscott** [comment]
@MaurizioPz Since these issues are pretty bite-size pieces and good for newcomers, I'd prefer if you chipped away at them one at a time instead of claiming them all at once, to give others the opportunity to contribute too. I'll assign this one to you for now, feel free to follow up with the others afterwards 👍
