### ISSUE TITLE
Add `groupBy` parameter to `IRepositoryReadConductor#FindAll`

### ISSUE THREAD

**Issue by mrjones2014** [AndcultureCode/AndcultureCode.CSharp.Core#48]
Currently, to use `GROUP BY` with the conductors, you have to read the results, then call `GroupBy` on the `ResultObject`. We should add a `groupBy` parameter to the `FindAll` methods that would group the `ResultObject` before returning it.

**Comment by brandongregoryscott** [comment]
Published with [v0.7.0](https://github.com/AndcultureCode/AndcultureCode.CSharp.Core/releases/tag/v0.7.0)
